package main

// ***IDENTIFICATION OF VARIABLES IN THE PROGRAM***
//
// 6480
var (
	// AMOUNT SPENT ON ANIMALS
	A float64

	// AMOUNT SPENT ON AMMUNITION
	B float64

	// ACTUAL RESPONSE TIME FOR INPUTTING "BANG"
	B1 float64

	// CLOCK TIME AT START OF INPUTTING "BANG"
	B3 float64

	// AMOUNT SPENT ON CLOTHING
	C float64

	// FLAG FOR INSUFFICIENT CLOTHING IN COLD WEATHER
	C1 int

	// C$ - YES/N0 RESPONSE TO QUESTIONS
	CS string

	// SELECTED EVENT
	D float64

	// COUNTER IN GENERATING EVENTS
	D1 int

	// TURN NUMBER FOR SETTING DATE
	D3 float64

	// CURRENT DATE
	D4 int

	// CHOICE OF SHOOTING EXPERTISE LEVEL
	D9 float64

	// CHOICE OF EATING
	E float64

	// AMOUNT SPENT ON FOOD
	F float64

	// FLAG FOR CLEARING SOUTH PASS
	F1 int

	// FLAG FOR CLEARING BLUE MOUNTAINS
	F2 int

	// FRACTION OF 2 WEEKS TRAVELED ON FINAL TURN
	F9 float64

	// FLAG FOR INJURY
	K8 int

	// FLAG FOR BLIZZARD
	L1 int

	// TOTAL MILEAGE WHOLE TRIP
	M float64

	// AMOUNT SPENT ON MISCELLANEOUS SUPPLIES
	M1 float64

	// TOTAL MILEAGE UP THROUGH PREVIOUS TURN
	M2 float64

	// FLAG FOR CLEARING SOUTH PASS IN SETTING MILEAGE
	M9 int

	// AMOUNT SPENT ON ITEMS AT FORT
	P float64

	// RANDOM NUMBER IN CHOOSING EVENTS
	R1 float64

	// FLAG FOR ILLNESS
	S4 int

	// "HOSTILITY OF RIDERS" FACTOR
	S5 int

	// SHOOTING WORD SELECTOR
	S6 float64

	// S$ - VARIATIONS OF SHOOTING WORD
	SS map[int]string

	// CASH LEFT OVER AFTER INITIAL PURCHASES
	T float64

	// CHOICE OF TACTICS WHEN ATTACKED
	T1 float64

	// CHOICE OF ACTION FOR EACH TURN
	X float64

	// FLAG FOR FORT OPTION
	X1 int
)
